### ISSUE TITLE
Options on Docker image

### ISSUE THREAD

**Issue by Soullivaneuh** [djfarrelly/MailDev#100]
Your application allow to set many options.

Would be great to be able to add it on the docker image, like the verbose one for example.

**Comment by djfarrelly** [comment]
Hi @Soullivaneuh! You should be able to override the command when running the container, i.e.

```
$ docker run -P 80:80 -P 25:25 djfarrelly/maildev bin/maildev --web 80 --smtp 25 --verbose
```

**Comment by Soullivaneuh** [comment]
Well, we ca indeed do that. But it's not really pretty IMO because you have to override all the command line with default options.

If on another version, you change the default command line for good reason, I would not see it.

**Comment by Soullivaneuh** [comment]
FYI, I'm running maildev with docker-compose:

```yml
maildev:
  image: djfarrelly/maildev
  ports:
    - '1080:80'
```

Would be great to deal with env section:

```yml
maildev:
  image: djfarrelly/maildev
  ports:
    - '1080:42'
  environment:
    - HTTP_PORT=25
    - SMTP_PORT=yes
    - VERBOSE=yes
```

With this method, env variable will be available for linked container too, this can provide useful information.

Are you interested of a PoC PR?

**Comment by djfarrelly** [comment]
Hey @Soullivaneuh, thanks for your thoughts and effort on this one. I'm a bit hesitant on this one as it simply adds another configuration mechanism where I don't personally see that it's too bad here to use the arguments as one would configure MailDev on the command line.

```yml
maildev:
  image: djfarrelly/maildev
  cmd: bin/maildev --web 80 --smtp 25 --verbose
  ports:
    - '1080:80'
```
or alternatively...
```yml
  cmd: bin/maildev
    --web 80 
    --smtp 25 
    --verbose
```

The approach may be "less pretty," but it's easy to maintain consistency with the project. I'll keep this open in case others want to chime in and share thoughts

**Comment by Soullivaneuh** [comment]
@djfarrelly Yes, this is what I used. But having options permit more flexibility.

If, for reason, one of my developers has to change only the web port, he actually has to override the full command and will get rid of any update about it.

With options, it will be able to change only the port and don't touch to the raw command.

So I really think having options give some advantages. Furthermore, most of the official Docker images use this way,

**Comment by Theon01** [comment]
Just a heads up :
`command` should be used instead of `cmd` in the most recent version of docker compose.

**Comment by curry684** [comment]
For the underlying discussion: especially when using deployments in for example Kubernetes you should not rely on command parametrization. [Config should be in the environment](https://12factor.net/config).

**Comment by oktapodia** [comment]
Thank you for your issue, we will gonna check into it.

**Comment by djfarrelly** [comment]
This is supported now. As of 3.0 the image reads `MAILDEV_*` environment variables, so you can configure it via the compose `environment:` section without overriding the command — e.g.:

```yaml
services:
  maildev:
    image: maildev/maildev
    environment:
      - MAILDEV_WEB_PORT=1080
      - MAILDEV_SMTP_PORT=1025
      - MAILDEV_VERBOSE=true
    ports:
      - "1080:1080"
      - "1025:1025"
```

Mapping lives in `packages/cli/src/config/env.ts` (ports, IPs, incoming/outgoing auth, HTTPS, verbose/silent, etc.), and the Dockerfile sets `MAILDEV_WEB_PORT`/`MAILDEV_SMTP_PORT` as defaults. Note the names are `MAILDEV_`-prefixed (`MAILDEV_WEB_PORT`, `MAILDEV_VERBOSE`, …), not the bare `HTTP_PORT`/`VERBOSE` from the original suggestion. Closing as resolved. (Follow-up: these env vars aren't yet listed in `docs/docker.md` — tracked separately under the Docker docs issue.)
