### ISSUE TITLE
Crashes when sending emails 1.0.0-rc1 (:latest tag) & 1.0.0-rc2

### ISSUE THREAD

**Issue by denji** [djfarrelly/MailDev#175]
Crash when sending mail - undefined behavior, the code is probably not in strict mode type checking.
* __0.14.0__ latest stable and working version.
* 1.0.0-rc1 (`djfarrelly/maildev:latest`) & 1.0.0-rc2 the shutdown signal with the `Could not start mail server on undefined:undefined`.

docker-compose.yml
----------------------------

```yml
version: '3'
services:
  maildev:
    image: djfarrelly/maildev:1.0.0-rc2
    #image: djfarrelly/maildev:1.0.0-rc1
    #image: djfarrelly/maildev:0.14.0
    command: env NODE_ENV=development bin/maildev --verbose
    environment:
     - NODE_ENV=development
```

> MailDev webapp running at http://0.0.0.0:80
> MailDev SMTP Server running at 0.0.0.0:25

Send email from the other container to smtp(`maildev:25`) SIGTERM

> Could not start mail server on __undefined:undefined__
> Port already in use or insufficient rights to bind port
> Recieved shutdown signal, shutting down now...

undefined?
